### ISSUE TITLE
config migrations and portable mode

### ISSUE THREAD

**Issue by caoyue** [caoyue/WindowResizer#11]
https://github.com/caoyue/WindowResizer/pull/8#issuecomment-890597837
1.  store config in the root of profile folder 
2.  portable mode option
    To put it simply, firstly check "WindowResizer.config.json" in app folder, 
    if exists, use it (Portable Mode);
    if not, check it in profile folder;
    both no, create it in app folder.

    and add a new option to move between two place;
    hope this solve the problem.

**Comment by rpodric** [comment]
Sounds good, thanks!
