### ISSUE TITLE
Restore window position automatically

### ISSUE THREAD

**Issue by lsaranto** [caoyue/WindowResizer#13]
Can you add an option to automatically restore the window position when launching the saved application?

**Comment by caoyue** [comment]
Will consider it, maybe scheduled for the next major version.

**Comment by caoyue** [comment]
Hi, a new version of this feature released.
You can download and test from here.
https://github.com/caoyue/WindowResizer/releases/download/0.4.52/window_resizer_0.4.52.zip

**Comment by Megas97** [comment]
@caoyue I am having trouble with the auto restore function. I have set my windows with CTRL+ALT+S as well as checked the 'Auto' option for each window & clicked 'Save' after that. The problem is that when I open a saved application back up (when I maximize it again) it does not restore it to the position and size saved with your program. Am I doing something wrong or? I absolutely hate how stupid Windows handles this and now that I got a new 4K monitor not all my games support it and some run at 1080p - meaning when I exit some games all my minimized programs have moved positions and sizes...

**Comment by caoyue** [comment]
> The problem is that when I open a saved application back up (when I maximize it again) it does not restore it to the position and size saved with your program. 

Currently the window is only automatically resized when it is created (otherwise it could become annoying).
So when you maximize or minimize a window, it is not considered as "created".
Maybe you can try the `restore all opened window position` shortcut keys?

**Comment by Megas97** [comment]
> 

Oh that makes sense why it's not working then. The "Restore all opened window position" option works if I have an open program but it maximizes all of the saved programs at once. Could you please add an option to automatically restore positions and sizes when a user maximizes a saved program from the taskbar? That would be perfect to once and for all fix all this window moving / changing when changing resolutions.

**Comment by caoyue** [comment]
> but it maximizes all of the saved programs at once

@Megas97  Did it not work as expected?  Could you please elaborate on this?

> Could you please add an option to automatically restore positions and sizes when a user maximizes a saved program from the taskbar? 

I'm not sure if it's possible to tell when a user maximizes a window from the taskbar...
I will look into this later.

**Comment by Megas97** [comment]
> > but it maximizes all of the saved programs at once
> 
> @Megas97 Did it not work as expected? Could you please elaborate on this?
> 
It does restore all programs to their saved states but it also maximizes all of them on my Desktop if they were minimized. Not sure if this is how it should be or not. Anyway thank you for the program as it still fixes the positions and sizes. Just wish it would do it automatically even when maximizing them from taskbar. I found this if it's of any help: https://stackoverflow.com/questions/19137937/how-to-detect-the-window-has-been-maximized
https://stackoverflow.com/questions/2006027/detect-all-windows-minimized-from-c-sharp-application
I know the first one is in C++ but maybe it can still help :)

**Comment by caoyue** [comment]
> It does restore all programs to their saved states but it also maximizes all of them on my Desktop if they were minimized. 

That's work as designed. The `restore all opened window position` shortcuts restore all opened windows even if there are minimized. 
Maybe an option can be added here to skip windows already minimized.

> Just wish it would do it automatically even when maximizing them from taskbar. 

Detect window maximized is possible, but it may be maximized from shortcuts, window maximize button or other, it's difficult to tell if is from taskbar...
So the program does not know if the user wants to actually maximize the window or resize it, anyway, I will look into it.

**Comment by Megas97** [comment]
@caoyue just so it's clear. By maximize i mean restore / open program from taskbar or shortcut, NOT actually making program window fill whole screen by clicking the maximize button at the top right of program window. 
Basically the same as what 'auto' option does but for when restoring program window of open program, not just when starting it from 0.
