### ISSUE TITLE
Not picking up windows

### ISSUE THREAD

**Issue by lsaranto** [caoyue/WindowResizer#17]
I'm having trouble getting WindowResizer to see most of the windows. It's basically just picking up its own Setting window. It's not picking up eg. Chrome, Notepad++, Windows Explorer or WinRAR. Is there a way to manually add a window other than by editing the JSON file? I tried editing the JSON file and some windows (eg. Notepad++) started to move when pressing Ctrl+Alt+R, so WindowResizer is sensing them.

How does the window matching work? Is the process name always required? Is it matched first?

Note: I am still using Windows 7 and it may be part of the issue, so I'm not sure how much time you want to invest in fixing this.

**Comment by caoyue** [comment]
I don't have a windows 7 device so I can't test it now.
I'll try to find one later to see if there is a bug on Windows 7.

> **how to add a config**

Focus on the window (eg. Chrome), then press the `save window` hotkey (`ctrl+alt+s` by default), an entry will be added to the json file, so you don't need to edit the json file manually.
If it doesn't work, there may be a bug here.

> **How does the window matching work? Is the process name always required? Is it matched first?**

Yes, a process name is always required and matched first.
The title is not required, by default use a wildcard * to match all the titles for a process name.
And if you specify the title, it will be matched first.

**Comment by lsaranto** [comment]
> > **how to add a config**
> 
> Focus on the window (eg. Chrome), then press the `save window` hotkey (`ctrl+alt+s` by default), an entry will be added to the json file, so you don't need to edit the json file manually. If it doesn't work, there may be a bug here.

Ok, I see, that's how it works. I assumed ctrl+alt+s was supposed to add all open windows. I can add all the "missing" windows by focusing them and pressing the shortcut. There's probably no bug in the first place then. Just my wrong assumption.

Might be worthwhile to add what you wrote above to the front page description.

**Comment by caoyue** [comment]
>  Might be worthwhile to add what you wrote above to the front page description.
Think so, will add it.
