### ISSUE TITLE
Please provide an installer and auto-updater

### ISSUE THREAD

**Issue by ziplock9000** [caoyue/WindowResizer#18]
As the title says

**Comment by Skyline404** [comment]
or choco package

**Comment by ziplock9000** [comment]
> or choco package

I think that's a bad move. The overwhelming amount of Windows users don't even know what that is, never mind how to use it.

**Comment by caoyue** [comment]
From version 1.0.1 you can install the app from the installer and have automatic updates.

Please check the release page:
[https://github.com/caoyue/WindowResizer/releases](https://github.com/caoyue/WindowResizer/releases)

Installer:
[https://github.com/caoyue/WindowResizer/releases/download/1.0.2/WindowResizer-1.0.2.exe](https://github.com/caoyue/WindowResizer/releases/download/1.0.2/WindowResizer-1.0.2.exe)

**Comment by ziplock9000** [comment]
> From version 1.0.1 you can install the app from the installer and have automatic updates.
> 
> Please check the release page: https://github.com/caoyue/WindowResizer/releases
> 
> Installer: https://github.com/caoyue/WindowResizer/releases/download/1.0.2/WindowResizer-1.0.2.exe

Excellent. I'll check this out thanks.

**Comment by rpodric** [comment]
Automatic updates? How would that work? I'm glad it's not a scheduled task or a service, since it's not really warranted, but how else could it happen? Does the program at some point pop up update notices?

**Comment by caoyue** [comment]
> Automatic updates? How would that work? I'm glad it's not a scheduled task or a service, since it's not really warranted, but how else could it happen? Does the program at some point pop up update notices?

It will check github release page for new updates at startup.
And if so, it will automatically download the update and install it.
