### ISSUE TITLE
Restore Maximised state and position properly

### ISSUE THREAD

**Issue by ziplock9000** [caoyue/WindowResizer#19]
Restoring a window that was maximised does not return it to a maximised state and does not put it in quite the right place

It thinks the window is at -11,-11 on one of my monitors.

Maximised window before restoring: https://i.imgur.com/bw3ockk.png

Restored Window: https://i.imgur.com/yq2nbyw.png

**Comment by caoyue** [comment]
It just saves the position of a window without its state now.

Under Windows, non-maximized windows have invisible borders on window left, top, right, bottom, it is used to grip the mouse for resizing, but no borders in a maximized state. 
So this problem occurs when you use the save and restore position with the window maximized.
Perhaps a workaround could be used here to solve this.

Alternatively, You can use the system's built-in shortcuts `Win+↑` to maximize the window and `Win+↓` to restore the window.

**Comment by ziplock9000** [comment]
I have 3 monitors and one of them is connected via DisplayPort, which means when I put it on standby the system thinks it's disconnected and puts all of my windows onto another monitor. This can happen several times a day with ~10 windows, thus close to 100 windows/day. 
So I need this tool to put the windows back where they were.
So unfortunately that workaround would be such a pain in the arse that it makes using the tool mostly unhelpful.
But to be honest, whatever Windows does with extra borders etc. A tool that is supposed to restore windows should really be doing that.

**Comment by ziplock9000** [comment]
I've been using PersistantWindows for about 18 months, which has code on Github or Bitbucket somewhere. Maybe you can look at that to fix this issue and other guidance.

**Comment by caoyue** [comment]
ok, I'll look into this later.

**Comment by caoyue** [comment]
Hope the new version will solve your problem.
https://github.com/caoyue/WindowResizer/releases/download/0.4.50/window_resizer_0.4.50.zip

**Comment by ziplock9000** [comment]
The position is now correct, but it does not return the window to the original monitor.

**Comment by caoyue** [comment]
sorry, support for multiple monitors is not in the current plan. 
Will consider this feature later.
