### ISSUE TITLE
WindowResizer not add in list "Everything"

### ISSUE THREAD

**Issue by lpslp** [caoyue/WindowResizer#25]
hi
if i try to save posiotion for program "Everything v1.3.4.686 x86" then WindowResizer-1.0.2 not add it at all

**Comment by lpslp** [comment]
strange that your program won't run "as administrator"

**Comment by caoyue** [comment]
Hi, I can't reproduce this issue with the same version of `Everything` and `WindowResizer`.
Can you provide the version information of your Windows?

**Comment by lpslp** [comment]
>version information of your Windows
21H2 (19044.1766)

just now checked again - chrome is added normal in WindowResizer, Explorer.exe is added normal WindowResizer but "Everything" - is not.

**Comment by caoyue** [comment]
Ok, I will try to see where the problem is.
Thank you for reporting this issue.
