### ISSUE TITLE
Streamlabs Chatbot - Version: 1.0.2.71

### ISSUE THREAD

**Issue by mentalmindgames** [caoyue/WindowResizer#26]
New user here. Loving the software, thank you! I've got a problem with just one of the applications I'm trying to save the position of. It's Streamlabs Chatbot. Seems to be working great with all the other software I'm using. Thanks again!

**Comment by caoyue** [comment]
Hi, I tried this software and found that it was running with administrator privileges.
This may be the reason for the issue.
You can try to run `WindowResizer` as administrator and see if that solves your problem.

**Comment by mentalmindgames** [comment]
That resolved the issue. Thanks!
