### ISSUE TITLE
Suggestion : adding profiles

### ISSUE THREAD

**Issue by remizik** [caoyue/WindowResizer#32]
Hi,
first of all, amazing application. Thanks a lot.
Would it be possible to add profiles ?
I'm using the application on my laptop and I have a different screen setup between the office and home.
Maybe two different "save all" & "restore all" shortcuts ?
Or a right clic on the tray icon to select "home" or "office" (or profile1/profile2).

Thanks :)

**Comment by caoyue** [comment]
Hi, this feature is under consideration.

**Comment by stepson** [comment]
Hello ! Also looking at this amazing tool I was about to start to code and I find it already existing ;-).
Same suggestion / remark. It would be fine to memorize 2 sets of windows (or more why not). For my daily usage I need 2 sets of windows positions based on how I split my windows between laptop screen and external screen. I have 2 typical positions and I would like to switch between the 2 with 2 shortcuts or same shorcut but moving to the next set of positions.
Also it seems there is a small bug with 2 screens. The windows do not restore on the correct screen.

**Comment by remizik** [comment]
> Also it seems there is a small bug with 2 screens. The windows do not restore on the correct screen.

You are correct, for fullscreen applications.
It's working fine for windowed applications though.
