### ISSUE TITLE
Does anyone see constant CPU usage until the process is restarted?

### ISSUE THREAD

**Issue by rpodric** [caoyue/WindowResizer#35]
I'm on the current version, and I've seen it happen with it, but this is not a new problem. When it happens, the process (on my system, an older Core i5) takes around 15% CPU permanently (well, until you close the app and restart it). Perhaps that translates to one core, I'm not sure.

And then all is well until some random time later, usually days, when it happens again. I haven't figured out what triggers this, though I do know that it's not after _any_ use of it, since I use it frequently (as in hotkey use).

Win11

**Comment by remizik** [comment]
It's fine here, computer has been running for a while 

![image](https://user-images.githubusercontent.com/24875086/190238014-969d3e54-aafb-483d-a75a-0ab61680bac2.png)

My CPU is an AMD Ryzen 7 3700X

**Comment by caoyue** [comment]
Can't reproduce this issue consistently yet, but I'll keep tracking it.

**Comment by rpodric** [comment]
No problem in closing it given that it stopped happening not too long afterwards.
