### ISSUE TITLE
[Feature Request] Automatically select profiles when the monitor setup changes

### ISSUE THREAD

**Issue by rwild003** [caoyue/WindowResizer#37]
As a user I'd like WindowResizer to automatically select profiles when the monitor setup changes and execute "Restore All", so that my saved window layout is automatically restored.

PersistentWindows could be a source for inspiration: https://github.com/kangyu-california/PersistentWindows

**Comment by caoyue** [comment]
I think this is a good feature too, will add it to the backlog.
