### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by mentalmindgames** [caoyue/WindowResizer#39]
Every time I open Window Resizer it says there is an update and when I click ok to download update I get an error. If that's not weird enough on its own I'm running v1.3.0 which from what I see here is the latest version. Any help would be appreciated.

**Comment by caoyue** [comment]
Maybe some reason interfered with the upgrade process, but I haven't reproduced it.
You can try uninstalling the program and reinstalling it.
Just in case, it is better to export and backup the configuration file first.

**Comment by remizik** [comment]
I can confirm I updated the application, and I got a "new update message" when I rebooted later, which failed since I already updated.

**Comment by remizik** [comment]
Hello,
any news on this ?
Still get this message and also a new desktop shortcut after every reboot : 

![image](https://user-images.githubusercontent.com/24875086/216151099-720f99aa-3f45-45f4-9602-dc002df2c605.png)

Thanks :)

**Comment by caoyue** [comment]
Sorry, the bug has not been reproduced yet 😂.
I will release a new version in the next few days, and see if the update problem still exists.

**Comment by remizik** [comment]
No worries!
Thanks for the coming update :) I'll report

**Comment by remizik** [comment]
Ignore me, I had an old shortcut in my shell:startup pointing to an old 1.2 version in a download folder...
That was the reason for this popup message.
I'm very sorry!

**Comment by caoyue** [comment]
> Ignore me, I had an old shortcut in my shell:startup pointing to an old 1.2 version in a download folder... That was the reason for this popup message. I'm very sorry!

It's okay, glad to hear that you solved the problem!
