### ISSUE TITLE
Portable Mode broken?

### ISSUE THREAD

**Issue by KBrownConsulting** [caoyue/WindowResizer#43]
I can't seem to get Portable Mode to work. 

When I enable the check box, if I exit WindowResizer & relaunch it, the option is unchecked again.

If I enable the option & try to Export the config I get the error: "An error occurred, check the log file for more details."

Bug, or am I doing it wrong?

Thanks

**Comment by caoyue** [comment]
Sorry for the late reply.
Due to the conflict with the automatic update function, the Portable Mode is temporarily broken.
A standalone portable package will be released later.

**Comment by caoyue** [comment]
Hi, a new portable package has been added from version 1.3.1.
You can check it here ➡️ [windowresizer-portable-1.3.1.zip](https://github.com/caoyue/WindowResizer/releases/tag/1.3.1)
