### ISSUE TITLE
[Bug] Wrong window size when the task bar is on top

### ISSUE THREAD

**Issue by ekugan** [caoyue/WindowResizer#45]
Some details:
3440x1440, task bar is on top, small icons are enabled.

How to reproduce:

1. open some windows
2. press Alt + Ctrl + S to save all
3. change the position of any window (or you can just skip this step)
4. press Alt + Ctrl + R to restore all

In my case 1/3 of the screen is window 1 and 2/3 of the screen is window 2.
After step 2 it looks like this:
![image](https://user-images.githubusercontent.com/48126305/221888950-3f42c7d8-ea02-433b-8a4d-2756b863293a.png)

And after step 4 it looks like this:
![image](https://user-images.githubusercontent.com/48126305/221889015-0a8211aa-1fdc-4b69-bc8f-d3ae287a8d59.png)

There is an extra space below the task bar, but it doesn't suppose to be here I believe.

**Comment by remizik** [comment]
I had the issue the other day, but I'm using two monitors.
Anyway, I couldn't find why so I just manually edited the pixel values in the WindowResizer menu.

**Comment by ekugan** [comment]
Yeah, there is a workaround to fix it manually, but I hope it will be fixed in the future releases :)

**Comment by caoyue** [comment]
I am using Windows 11, which does not support setting the taskbar at the top of the screen (how stupid 😂), so I haven't tested this.
Probably know where the problem could be, I'll see how to fix it.
