### ISSUE TITLE
[Feature Request] Add an option to include minimized windows when restoring all windows 

### ISSUE THREAD

**Issue by remizik** [caoyue/WindowResizer#46]
I noticed an issue.

How to reproduce : 
1- Save your windows setup 
2- Move a window and reduce it
3- Restore the windows position with the hotkey
4- All the windows go back to their original position, except the one that is reduced.

You have to un-reduce it and then press the hotkey again to restore it to the desired position.

It would be great if pressing the hotkey would un-reduce and restore the window position directly :)

Thanks

**Comment by caoyue** [comment]
Hi, by “reduce” do you mean minimize the window?

**Comment by remizik** [comment]
> Hi, by “reduce” do you mean minimize the window?

yes, sorry :D

**Comment by caoyue** [comment]
If so, then this was designed that way, to avoid too many windows suddenly appear in the workspace.
Maybe add an option `Include minimized window` to restore minimized windows? Suggestions are welcome.
It’ll be available on the next minor release.

**Comment by remizik** [comment]
> If so, then this was designed that way, to avoid too many windows suddenly appear in the workspace. Maybe add an option `Include minimized window` to restore minimized windows? Suggestions are welcome. It’ll be available on the next minor release.

An option would be ideal. Thanks !
