### ISSUE TITLE
Suggestion: menu for Save all / Restore all 

### ISSUE THREAD

**Issue by florianhof** [caoyue/WindowResizer#57]
Helllo, 
First thanks for this very practical tool!
In the Status, WindowResizer has a menu with the profiles, settings, exit. It would be nice to have there also the "restore all" (which I mostly use) and "save all" functionalities. 
By the way, are there functional limitations on the "portable" version?

**Comment by caoyue** [comment]
> By the way, are there functional limitations on the "portable" version?

Currently, the portable version has all the features except for automatically update.
