### ISSUE TITLE
Apply also to taskbar

### ISSUE THREAD

**Issue by ebrouen** [caoyue/WindowResizer#59]
### Discussed in https://github.com/caoyue/WindowResizer/discussions/58

<div type='discussions-op-text'>

<sup>Originally posted by **ebrouen** May  6, 2023</sup>
I started to use WindowResizer a short time ago and I do appreciate it a lot.
A very nice improvement would be to be able to 'resize' (in fact better said 'reorder') the taskbars. 

If there is 2 or more monitor, the manual process involves 

- unlocking all the taskbars, 
- moving the primary taskbar (where the systray is reachable) 
- and again lock all the taskbars.

This process is necessary if you change from a multi-monitor configuration to a single monitor configuration, like taking your laptop with you, and back. 
Of course, it's not a very big job, but resizing a window is not a big job and still we appreciate WindowResizer...
</div>

**Comment by caoyue** [comment]
Tweaking taskbar is not the current goal of the software, but I will add it to the backlog.
However, due to Microsoft's "improvements" to the taskbar in Windows11, I have not found the relevant API yet 😂.
I will keep an eye on it.
