### ISSUE TITLE
Window not detected

### ISSUE THREAD

**Issue by Fr0stX76** [caoyue/WindowResizer#64]
Hi,

Somehow it seems like the sensor window of HWinfo64 is not detected. When I open the main program, it is indeeed detected, but when I try to do the same to the sensor panel (which is the one I would like to resize automatically) , it just doesnt get detected at all.

Not sure if I`m missing something or if it is just not compatible..

**Comment by DfrostX** [comment]
Reactivated :)

**Comment by caoyue** [comment]
Sorry for the late reply.
Can you provide an example of a reproduction? Or a program name which you encountered this problem with.
