### ISSUE TITLE
Resize Chrome New Windows

### ISSUE THREAD

**Issue by dragoncity17** [caoyue/WindowResizer#66]
Hello,

Your app is Amazing !!! Thanks a lot !!! :)

I use with "Chrome" and "Title", it work if I use "Hotkeys" but not in AUTO when I do "Open link in new windows".

How do that in "Auto" when I open an link in "New Windows" ?

Again thanks a lot... ! :)

**Comment by dragoncity17** [comment]
I found need use title "Sans titre - Google Chrome" in French for example ! :)

**Comment by dragoncity17** [comment]
Not perfect again but can use also "Custom Button" :
https://chrome.google.com/webstore/detail/custom-button/mphgmadkligoedhahoinkjghofkpmedf

**Comment by caoyue** [comment]
Sorry for the late reply.
I think it's a good feature, but it needs a lot of details to be considered inside.
I can't promise to implement it soon, I'll add it to my backlog.
Thank you for your suggestions!
