### ISSUE TITLE
hot key to restore all window

### ISSUE THREAD

**Issue by super-lurker** [caoyue/WindowResizer#9]
hot key to restore all window active or not on desktop

**Comment by mgoffin** [comment]
Would also love to have this feature! Looks like some potentially useful code to get all open window titles and handles here: https://stackoverflow.com/a/43640787.

**Comment by caoyue** [comment]
> Would also love to have this feature! Looks like some potentially useful code to get all open window titles and handles here: [stackoverflow.com/a/43640787](https://stackoverflow.com/a/43640787).

Thanks. I'll look into it later.

**Comment by caoyue** [comment]
Hi, just released a new version about this feature.
You can download and test it from [here].(https://github.com/caoyue/WindowResizer/releases/download/0.4.38/window_resizer_0.4.38.zip)
